In [47]:
#Importing Libraries
import pandas as pd
!pip install datasets
from datasets import load_dataset

import matplotlib.pyplot as plt

Requirement already satisfied: datasets in c:\users\aman\anaconda3\lib\site-packages (5.0.0)
Requirement already satisfied: filelock in c:\users\aman\anaconda3\lib\site-packages (from datasets) (3.20.0)
Requirement already satisfied: numpy>=1.17 in c:\users\aman\anaconda3\lib\site-packages (from datasets) (2.3.5)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\aman\anaconda3\lib\site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\users\aman\anaconda3\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in c:\users\aman\anaconda3\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\aman\anaconda3\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in c:\users\aman\anaconda3\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\aman\anaconda3\lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in c:\users\aman\anaconda3\lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in c:\users\aman\anaconda3\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in c:\users\aman\anaconda3\lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\users\aman\anaconda3\lib\site-packages (from datasets) (1.18.0)
Requirement already satisfied: packaging in c:\users\aman\anaconda3\lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\aman\anaconda3\lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\aman\anaconda3\lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: anyio in c:\users\aman\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (4.10.0)
Requirement already satisfied: certifi in c:\users\aman\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\aman\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\aman\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\aman\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click>=8.4.0 in c:\users\aman\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\aman\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in c:\users\aman\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.20.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\aman\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\aman\anaconda3\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\aman\anaconda3\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (14.2.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\aman\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\aman\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\aman\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\aman\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\aman\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\aman\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\aman\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: colorama in c:\users\aman\anaconda3\lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\aman\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\aman\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\aman\anaconda3\lib\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\aman\anaconda3\lib\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\aman\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Requirement already satisfied: sniffio>=1.1 in c:\users\aman\anaconda3\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aman\anaconda3\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aman\anaconda3\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aman\anaconda3\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\aman\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [48]:
#Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

In [49]:
#Data Cleaning
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [50]:
df.sample(5).head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
373411,Software Engineer,Senior React Native Developer,Jordan,via Jordan.tanqeeb.com,Full-time,False,Jordan,2023-01-09 18:33:53,False,False,Jordan,None,NaN,NaN,ArabWork,"['javascript', 'typescript', 'react']","{'libraries': ['react'], 'programming': ['java..."
333746,Senior Data Engineer,Senior Data Engineer - Hybrid/Bristol - Up to ...,United Kingdom,via WJHL Jobs,Full-time,False,United Kingdom,2023-07-03 23:13:51,False,False,United Kingdom,None,NaN,NaN,Adecco,"['sql', 'python', 'postgresql', 'redis', 'couc...","{'analyst_tools': ['tableau', 'power bi'], 'cl..."
337814,Data Analyst,Data Analytics (3),India,via LinkedIn,Contractor and Temp work,False,India,2023-10-03 23:13:38,False,False,India,None,NaN,NaN,International Maize and Wheat Improvement Cent...,"['c', 'r', 'python']","{'programming': ['c', 'r', 'python']}"
616546,Data Scientist,AI/ML data Scientist - Contract to Hire,Anywhere,via Upwork,Contractor,True,"Texas, United States",2023-03-22 12:11:44,False,False,United States,None,NaN,NaN,Upwork,"['python', 'r']","{'programming': ['python', 'r']}"
448780,Data Scientist,Data Scientist,"Gurugram, Haryana, India",via BeBee India,Full-time,False,India,2023-03-12 14:16:43,False,False,India,None,NaN,NaN,United Airlines,"['sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [51]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [52]:
df.index.name = 'job_index'

In [53]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [54]:
df.index.dtype

dtype('int64')

Three Methods to cover

In [55]:
df_usa = df[df['job_country'] == 'United States']

In [56]:
df_usa.reset_index(inplace=True)

df_usa

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
2,5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
3,6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
4,9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206287,785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,None,NaN,NaN,JPMorgan Chase & Co.,None,None
206288,785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,None,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
206289,785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
206290,785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,None,NaN,NaN,Axelon Services Corporation,None,None
206291,785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,None,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [57]:
df_usa.set_index('job_index', inplace=True)

In [58]:
df_usa

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,None,NaN,NaN,JPMorgan Chase & Co.,None,None
785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,None,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,None,NaN,NaN,Axelon Services Corporation,None,None
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,None,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [59]:
median_pivot = df_usa.pivot_table(index='job_title_short', values='salary_year_avg', aggfunc=['median', 'min', 'max'])

In [60]:
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  90000.0         35000.0        387460.0
Cloud Engineer                   116100.0         42000.0        221844.0
Data Analyst                      90000.0         25000.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Data Scientist                   130000.0         30000.0        960000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Analyst              110000.0         35360.0        425000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Senior Data Scientist            155000.0         55000.0        475000.0
Software Engineer                130000.0         48982.0        375000.0

In [61]:
median_pivot.sort_values(by=('median', 'salary_year_avg'), ascending=False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist            155000.0         55000.0        475000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Data Scientist                   130000.0         30000.0        960000.0
Software Engineer                130000.0         48982.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Cloud Engineer                   116100.0         42000.0        221844.0
Senior Data Analyst              110000.0         35360.0        425000.0
Business Analyst                  90000.0         35000.0        387460.0
Data Analyst                      90000.0         25000.0        375000.0

In [63]:
median_pivot.sort_index(inplace=True)

In [64]:
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  90000.0         35000.0        387460.0
Cloud Engineer                   116100.0         42000.0        221844.0
Data Analyst                      90000.0         25000.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Data Scientist                   130000.0         30000.0        960000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Analyst              110000.0         35360.0        425000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Senior Data Scientist            155000.0         55000.0        475000.0
Software Engineer                130000.0         48982.0        375000.0